export const STORES = [
  { id: "025", name: "Westmont" },
  { id: "041", name: "Marietta" },
  { id: "045", name: "St. Louis Park" },
  { id: "051", name: "Mayfield Heights" },
  { id: "055", name: "Madison Heights" },
  { id: "061", name: "St. Davids" },
  { id: "065", name: "Duluth" },
  { id: "071", name: "Sharonville" },
  { id: "075", name: "North Jersey" },
  { id: "081", name: "Fairfax" },
  { id: "085", name: "Rockville" },
  { id: "095", name: "Brentwood" },
  { id: "101", name: "Tustin" },
  { id: "105", name: "Yonkers" },
  { id: "115", name: "Brooklyn" },
  { id: "121", name: "Cambridge" },
  { id: "125", name: "Parkville" },
  { id: "131", name: "Dallas" },
  { id: "141", name: "Columbus" },
  { id: "145", name: "Flushing" },
  { id: "151", name: "Chicago" },
  { id: "155", name: "Houston" },
  { id: "165", name: "Indianapolis" },
  { id: "171", name: "Westbury" },
  { id: "175", name: "Charlotte" },
  { id: "181", name: "Denver" },
  { id: "185", name: "Miami" },
  { id: "191", name: "Overland Park" },
  { id: "195", name: "Santa Clara" },
  { id: "205", name: "Phoenix" },
];