name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # 1. ADD THIS BLOCK
    # Note: If 'Micro-SKU-APP' is the name of your GitHub repository itself, 
    # change this path to just './MicroScraper/android'
    defaults:
      run:
        working-directory: ./Micro-SKU-APP/MicroScraper/android

    steps:
    - uses: actions/checkout@v4
    
    # 2. PRO TIP: You may need to change this to Java 17
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
